version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
      - migrator
    environment:
      - PGHOST=${DB_HOST}
      - PGPORT=${DB_PORT}
      - PGDATABASE=${DB_NAME}
      - PGUSER=${DB_USER}
      - PGPASSWORD=${DB_PASSWORD}
    networks:
      - app-network
    restart: always

  db:
    image: postgres:15.6
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "6432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 5s
      timeout: 3s
      retries: 10

  migrator:
    image: migrate/migrate:v4.17.1
    depends_on:
      - db
    volumes:
      - ./db/migrations:/migrations
    command:
      - "-path=/migrations"
      - "-database"
      - "postgres://${DB_USER}:${DB_PASSWORD}@db:${DB_PORT}/${DB_NAME}?sslmode=disable"
      - "up"
    restart: on-failure
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
